# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='created_by',
        ),
    ]
