# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_remove_study_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study', to=settings.AUTH_USER_MODEL),
        ),
    ]
