# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_study_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
    ]
