# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-06 18:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20181202_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='responses',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None), size=8),
        ),
    ]
