# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0005_auto_20181206_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('att1', models.DecimalField(decimal_places=4, max_digits=5)),
                ('att2', models.DecimalField(decimal_places=4, max_digits=5)),
                ('att3', models.DecimalField(decimal_places=4, max_digits=5)),
                ('att4', models.DecimalField(decimal_places=4, max_digits=5)),
                ('att5', models.DecimalField(decimal_places=4, max_digits=5)),
                ('att6', models.DecimalField(decimal_places=4, max_digits=5)),
                ('att7', models.DecimalField(decimal_places=4, max_digits=5)),
                ('att8', models.DecimalField(decimal_places=4, max_digits=5)),
                ('att9', models.DecimalField(decimal_places=4, max_digits=5)),
                ('att10', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='response',
            name='for_survey',
        ),
        migrations.RemoveField(
            model_name='results',
            name='for_survey',
        ),
        migrations.RemoveField(
            model_name='study',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='in_study',
        ),
        migrations.AddField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.DeleteModel(
            name='Study',
        ),
        migrations.AddField(
            model_name='profile',
            name='in_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='survey.Survey'),
        ),
    ]
