# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20181206_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
    ]
