# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_tfresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfresult',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
