# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_design_questions_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='created_by',
        ),
    ]
