# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20181230_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfresult',
            name='name',
        ),
    ]
