# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20181230_2023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TFResult2',
        ),
    ]
