# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-31 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20181231_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='in_study',
            new_name='in_survey',
        ),
        migrations.AlterField(
            model_name='design',
            name='att10_type',
            field=models.IntegerField(blank=True, default=b'-1'),
        ),
        migrations.AlterField(
            model_name='design',
            name='att1_type',
            field=models.IntegerField(blank=True, default=b'-1'),
        ),
        migrations.AlterField(
            model_name='design',
            name='att2_type',
            field=models.IntegerField(blank=True, default=b'-1'),
        ),
        migrations.AlterField(
            model_name='design',
            name='att3_type',
            field=models.IntegerField(blank=True, default=b'-1'),
        ),
        migrations.AlterField(
            model_name='design',
            name='att4_type',
            field=models.IntegerField(blank=True, default=b'-1'),
        ),
        migrations.AlterField(
            model_name='design',
            name='att5_type',
            field=models.IntegerField(blank=True, default=b'-1'),
        ),
        migrations.AlterField(
            model_name='design',
            name='att6_type',
            field=models.IntegerField(blank=True, default=b'-1'),
        ),
        migrations.AlterField(
            model_name='design',
            name='att7_type',
            field=models.IntegerField(blank=True, default=b'-1'),
        ),
        migrations.AlterField(
            model_name='design',
            name='att8_type',
            field=models.IntegerField(blank=True, default=b'-1'),
        ),
        migrations.AlterField(
            model_name='design',
            name='att9_type',
            field=models.IntegerField(blank=True, default=b'-1'),
        ),
    ]
