# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-31 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20181231_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='in_study',
            new_name='in_survey',
        ),
        migrations.AlterField(
            model_name='design',
            name='att10_name',
            field=models.CharField(blank=True, default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='design',
            name='att1_name',
            field=models.CharField(blank=True, default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='design',
            name='att2_name',
            field=models.CharField(blank=True, default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='design',
            name='att3_name',
            field=models.CharField(blank=True, default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='design',
            name='att4_name',
            field=models.CharField(blank=True, default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='design',
            name='att5_name',
            field=models.CharField(blank=True, default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='design',
            name='att6_name',
            field=models.CharField(blank=True, default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='design',
            name='att7_name',
            field=models.CharField(blank=True, default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='design',
            name='att8_name',
            field=models.CharField(blank=True, default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='design',
            name='att9_name',
            field=models.CharField(blank=True, default=b'', max_length=30),
        ),
    ]
