# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-31 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20181231_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='in_survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='survey.Survey', unique=True),
        ),
    ]
