# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_merge_20190101_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='created_by',
            new_name='owner',
        ),
    ]
