# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20190101_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
