# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_survey_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
