# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-05 23:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20190103_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='att1_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=5), null=True, size=10),
        ),
    ]
