# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-06 16:06
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_auto_20190106_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='att10_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, default=b'-1', max_digits=5), null=True, size=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='att2_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, default=b'-1', max_digits=5), null=True, size=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='att3_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, default=b'-1', max_digits=5), null=True, size=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='att4_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, default=b'-1', max_digits=5), null=True, size=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='att5_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, default=b'-1', max_digits=5), null=True, size=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='att6_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, default=b'-1', max_digits=5), null=True, size=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='att7_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, default=b'-1', max_digits=5), null=True, size=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='att8_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, default=b'-1', max_digits=5), null=True, size=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='att9_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, default=b'-1', max_digits=5), null=True, size=10),
        ),
    ]
